include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    # Temporarily disable.
    public_member_api_docs: false
    lines_longer_than_80_chars: ignore
    avoid_positional_boolean_parameters: ignore
